/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cbtis270.programacion.compile_error;

import javax.swing.ImageIcon;

/**
 *
 * @author User
 */
public class Screen1 extends javax.swing.JFrame {

    String[] titles = new String[4];
    
    String[] langs = new String[4];
    
    int clicks_titl = 2;
    
    int clicks_lang = 1;
    
    String current = "en";
    
    Translator Translator1 = new Translator();
    
    SpeechRecognizer SpeechRecognizer1 = new SpeechRecognizer();
    
    
    
    /**
     * Creates new form Screen1
     */
    public Screen1() {
        initComponents();
        
        titles[0] = "Simple Translate";
        titles[1] = "Tradutor Simples";
        titles[2] = "Traductor Simple";
        titles[3] = "Traducteur Simple";
        
        langs[0] = "en";
        langs[1] = "pt";
        langs[2] = "es";
        langs[3] = "fr";
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txtlogo = new javax.swing.JLabel();
        Title = new javax.swing.JLabel();
        Logo = new javax.swing.JLabel();
        Icon = new javax.swing.JLabel();
        txtbox = new javax.swing.JTextField();
        txtbtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtTranslate = new javax.swing.JTextArea();
        translatelogo = new javax.swing.JLabel();
        tolang = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(320, 505));
        setMinimumSize(new java.awt.Dimension(320, 505));
        setPreferredSize(new java.awt.Dimension(320, 505));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(25, 32, 71));
        jPanel1.setForeground(new java.awt.Color(25, 32, 71));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 22, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(230, 230, 230));
        jPanel2.setForeground(new java.awt.Color(230, 230, 230));

        txtlogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cbtis270/programacion/img/icontranslate.png"))); // NOI18N
        txtlogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtlogoMouseClicked(evt);
            }
        });

        Title.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title.setText("Traductor Simple");

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cbtis270/programacion/img/logo.png"))); // NOI18N

        Icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cbtis270/programacion/img/icon.png"))); // NOI18N
        Icon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IconMouseClicked(evt);
            }
        });

        txtbox.setBackground(new java.awt.Color(255, 255, 255));

        txtbtn.setBackground(new java.awt.Color(25, 32, 71));
        txtbtn.setForeground(new java.awt.Color(25, 32, 71));
        txtbtn.setText("✔");
        txtbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtbtnMouseClicked(evt);
            }
        });

        txtTranslate.setEditable(false);
        txtTranslate.setBackground(new java.awt.Color(255, 255, 255));
        txtTranslate.setColumns(20);
        txtTranslate.setRows(5);
        jScrollPane1.setViewportView(txtTranslate);

        translatelogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cbtis270/programacion/img/translator.png"))); // NOI18N
        translatelogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                translatelogoMouseClicked(evt);
            }
        });

        tolang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cbtis270/programacion/img/en-flag.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Icon)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Logo))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(txtlogo))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtbox, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(translatelogo)
                            .addComponent(tolang))))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Icon)
                    .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Logo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtlogo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtbox, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(translatelogo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tolang)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IconMouseClicked
        clicks_titl ++;
        
        if(clicks_titl > 3){
        
            clicks_titl = 0;
            
            }
        
        Title.setText(titles[clicks_titl]);
        
    }//GEN-LAST:event_IconMouseClicked

    private void txtlogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtlogoMouseClicked
     
    SpeechRecognizer1.getText();
    txtbox.setText(SpeechRecognizer1.result);
        
    Translator1.requestTranslation(current, SpeechRecognizer1.result);
    
    txtTranslate.setText(Translator1.gotTranslation());
    
    }//GEN-LAST:event_txtlogoMouseClicked

    private void translatelogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_translatelogoMouseClicked
        clicks_lang ++;
        if(clicks_lang > 3){
        
            clicks_lang = 0;
            
            }
        current = langs[clicks_lang];
        
        System.out.println("Cambio de idioma, actual: "+current);
        
    }//GEN-LAST:event_translatelogoMouseClicked

    private void txtbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtbtnMouseClicked
    Translator1.requestTranslation(current, txtbox.getText());
    
    txtTranslate.setText(Translator1.gotTranslation());
    }//GEN-LAST:event_txtbtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Screen1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Screen1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Screen1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Screen1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Screen1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Icon;
    private javax.swing.JLabel Logo;
    private javax.swing.JLabel Title;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel tolang;
    private javax.swing.JLabel translatelogo;
    private javax.swing.JTextArea txtTranslate;
    private javax.swing.JTextField txtbox;
    private javax.swing.JButton txtbtn;
    private javax.swing.JLabel txtlogo;
    // End of variables declaration//GEN-END:variables
}
